name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: main.tex
      - name: Push compiled document
        uses: actions-go/push@master
        with:
          commit-message: '[Auto] Update compiled document'
          remote: origin
