name: Build LaTeX document
on:
  push:
    branches: [ main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            [One-Sided] Autonomous and Adaptive Systems Course Notes.tex
            [Two-Sided] Autonomous and Adaptive Systems Course Notes.tex
      - name: Push updated documents
        run: |
          git config --global user.name 'Alessandro Pomponio'
          git config --global user.email '10339005+AlessandroPomponio@users.noreply.github.com'
          git add *.pdf
          git commit -m "[AUTO] Update document"
          git push
