name: Build LaTeX document
on:
  push:
    branches: [ main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            [One-Sided] Autonomous and Adaptive Systems Course Notes.tex
            [Two-Sided] Autonomous and Adaptive Systems Course Notes.tex
      - name: Push compiled document
        uses: actions-go/push@master
        with:
          commit-message: '[Auto] Update compiled document'
          remote: origin
