name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            [One-Sided] Autonomous and Adaptive Systems Course Notes.tex
            [Two-Sided] Autonomous and Adaptive Systems Course Notes.tex
      - name: Push updated documents
        run: |
          git config --global user.name 'Alessandro Pomponio'
          git config --global user.email 'alessandro.pomponio2@studio.unibo.it'
          git commit -m "[AUTO] Update document" "[One-Sided] Autonomous and Adaptive Systems Course Notes.pdf" "[Two-Sided] Autonomous and Adaptive Systems Course Notes.pdf"
          git push
